services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_apache_server
    volumes:
      - .:/var/www
    ports:
      - "8000:80"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_USER=user
      - DB_PASSWORD=password
      - DB_NAME=user_registration
    networks:
      - backend
    restart: always

  db:
    image: mysql:8.0
    container_name: mysql_server
    environment:
      MYSQL_DATABASE: user_registration
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - backend
    restart: always

  adminer:
    image: adminer
    container_name: adminer_server
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    networks:
      - backend

networks:
  backend:

volumes:
  mysql_data: